// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/portfolio/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/portfolio" | "/portfolio/:projectId" | "/contact";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/about" | "/portfolio" | "/portfolio/:projectId" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/portfolio.tsx": {
    id: "routes/portfolio";
    page: "/portfolio";
  };
  "./routes/portfolio.$projectId.tsx": {
    id: "routes/portfolio.$projectId";
    page: "/portfolio/:projectId";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/layout": typeof import("./app/routes/layout.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/portfolio": typeof import("./app/routes/portfolio.tsx");
  "routes/portfolio.$projectId": typeof import("./app/./routes/portfolio.$projectId.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
};